
// API 1
//Scenario 1
//Returns a list of all todos whose status is 'TO DO'
GET http://localhost:3000/todos/?status=TO%20DO


###
//Scenario 2
//Returns a list of all todos whose priority is 'HIGH'
GET http://localhost:3000/todos/?priority=HIGH

###
//Scenario 3
//Returns a list of all todos whose priority is 'HIGH' and status is 'IN PROGRESS'
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###
//Scenario 4
//Returns a list of all todos whose todo contains 'CSS' text
GET http://localhost:3000/todos/?search_q=Buy

###
//Scenario 5
//Returns a list of all todos whose category is 'WORK' and status is 'DONE'
GET http://localhost:3000/todos/?category=WORK&status=DONE

###
//Scenario 6
//Returns a list of all todos whose category is 'HOME'
GET http://localhost:3000/todos/?category=HOME

###
//Scenario 7
//Returns a list of all todos whose category is 'LEARNING' and priority is 'HIGH'
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###
// API 2
//Returns a specific todo based on the todo ID
GET http://localhost:3000/todos/1/

###
// API 3
//Returns a list of all todos with a specific due date in the query parameter /agenda/?date=2021-12-12
GET http://localhost:3000/agenda/?date=2021-01-12

###
// Create a todo in the todo table, 
//API 4
POST http://localhost:3000/todos/

Content-Type: application/json
{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}

###
//API 5
//Updates the details of a specific todo based on the todo ID

//SCENARIO 1
//Status Updated
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
 "status": "DONE" 
}

###
//SCENARIO 2
//Priority Updated
PUT http://localhost:3000/todos/:todoId/
Content-Type: application/json

{
"priority": "HIGH" 
}

###
//SCENARIO 3
//Todo Updated
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
 "todo": "Some task"
}

###
//SCENARIO 4
//Category Updated
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
 "category": "LEARNING"
}

###
//SCENARIO 5
//Due Date Updated
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
"dueDate": "2021-01-12" 
}


###
// API 6
//Deletes a todo from the todo table based on the todo ID
DELETE http://localhost:3000/todos/10/
